import Zcash.Circuits.Integration.CopyPermutation
import Zcash.Common.RelationWitness
import Zcash.Circuits.Integration.PermutationColumns

/-!
# Circuit-generic permutation-cycle construction

This module identifies the common-permutation polynomials routed from the
accepted verifier relation with the σ columns generated by circuit keygen. It
then constructs the exact `ResolverPermutationCycle` consumed by the generic
copy semantics, retaining only the shared augmented-commitment relation branch.

All large objects remain in their compiler-native index types. The sole domain
size equality is discharged by the generic size-transport theorem in
`PermutationColumns`.
-/

open Zcash.Arithmetic (omegaOf)

namespace Zcash.Snark

open Zcash.Arithmetic (derivedUrsGLagrange omegaOf)

open Halo2 CompPoly.CPolynomial
open Keygen

namespace TopLevelCopy

variable {Config : Type} {PublicInput : TypeMap} [ProvableType PublicInput]
  (top : TopLevelCircuit Fp Config PublicInput) [TopLevelShape top]

variable {G : Type} [AddCommGroup G] [Module Fp G]
  [DecidableEq G] [Inhabited G]

theorem copyList_decoded :
    Halo2.Layout.V1.copyList
        (Halo2.Layout.permColsOf top.constraintSystem)
        (Halo2.FloorPlanner.V1.starts
          (top.operations))
        (top.operations)
        (Halo2.Layout.constantCopyEntries top.constraintSystem
          (top.operations)) =
      (pairs top).map fun pair =>
        (pair.1.pair.1, pair.1.pair.2,
          pair.2.pair.1, pair.2.pair.2) := by
  have hdecode :=
    (Zcash.Snark.decodeCopies_map
      top.permutationColumnCount
      top.n
      top.copyPairs
      (copyBounds top)).symm
  simpa only [TopLevelCircuit.copyPairs,
    columns, constants,
    TopLevelCircuit.regionStarts] using hdecode

omit [Module Fp G] [DecidableEq G] in
theorem permutationRows_eq_chunkRowName
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin pp.numProofs)
    (chunk : Fin top.permutationSetCount)
    (column : Fin
      (ResolverPermutationPairs
        (top.toVerifierKey urs) poly proofIndex chunk).length)
    (row : Fin top.n) :
    (Zcash.Snark.topLevelPermutationRows
      top
      (((chunkFlatten top) pp urs poly proofIndex
        ⟨chunk, row, column⟩).2 : ℕ)).getD (row : ℕ) 0 =
      chunkRowName
        top.omega
        Zcash.Arithmetic.deltaFp
        top.chunkLen
        (((fullSigma top) pp urs poly proofIndex
          ⟨chunk, row, column⟩).1 : ℕ)
        (((fullSigma top) pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.1 : ℕ)
        (((fullSigma top) pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.2 : ℕ) := by
  rw [TopLevelCircuit.omega, Zcash.Arithmetic.pastaDomain_omega_eq]
  apply Zcash.Snark.Layout.Asm.permPolysOf_getD_eq_chunkRowName
    top.constraintSystem
    (top.operations)
    (columns_length top).symm
    top.n_eq_two_pow_domainExponent
    (pairs top)
    (copyList_decoded top)
    top.chunkLen
    ((chunkFlatten top) pp urs poly proofIndex)
  · intro rc
    exact congrArg Fin.val
      ((chunkFlatten_symm_apply_row top)
        pp urs poly proofIndex rc)
  · intro rc
    exact (chunkFlatten_symm_apply_column top)
      pp urs poly proofIndex rc

theorem zipIdx_getD_snd
    {α : Type} (xs : List α) (fallback : α)
    (index : ℕ) (hindex : index < xs.length) :
    (xs.zipIdx.getD index (fallback, 0)).2 = index := by
  rw [List.getD_eq_getElem _ _ (by simpa using hindex)]
  simp

omit [Module Fp G] [DecidableEq G] in
theorem chunkCommonIndex
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin pp.numProofs)
    (chunk : Fin top.permutationSetCount)
    (column : Fin
      (ResolverPermutationPairs
        (top.toVerifierKey urs) poly proofIndex chunk).length) :
    ((top.verifierCS.permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
      (chunk : ℕ) * top.chunkLen + (column : ℕ) := by
  rw [← top.toVerifierKey_permutationChunks urs]
  let vk := top.toVerifierKey urs
  let global : ℕ :=
    (chunk : ℕ) * top.chunkLen + (column : ℕ)
  have hchunk :
      (chunk : ℕ) < vk.permutationChunks.length := by
    rw [top.toVerifierKey_permutationChunks_length]
    exact chunk.isLt
  have hcolumn :
      (column : ℕ) <
        (vk.permutationChunks.getD chunk []).length := by
    simpa only [ResolverPermutationPairs,
      permutationChunkPairsOfResolver, List.length_map] using column.isLt
  have hprefix :
      (vk.permutationChunks.take chunk).flatten.length =
        (chunk : ℕ) * vk.chunkLen := by
    exact top.toVerifierKey_permutationChunks_take_flatten_length
      urs chunk hchunk
  have hglobal :
      global <
        top.permutationColumnCount := by
    have h :=
      (((chunkFlatten top) pp urs poly proofIndex
        ⟨chunk, ⟨0, top.n_pos⟩, column⟩).2).isLt
    simpa only [global,
      chunkFlatten_apply_column,
      columns_length] using h
  have hglobalIndex :
      (vk.permutationChunks.take chunk).flatten.length +
          (column : ℕ) =
        global := by
    rw [hprefix]
    simp only [vk, global,
      top.toVerifierKey_chunkLen]
  have hlocal :=
    Zcash.Snark.flatten_getD_at_chunk
      ((.advice 0), 0) vk.permutationChunks
      chunk column
      hchunk
      hcolumn
  rw [hglobalIndex] at hlocal
  have hflatten :
      vk.permutationChunks.flatten =
      (top.permutationColumns.map
          (Zcash.Snark.permutationQueryReference
            top.adviceQueryLayout
            top.fixedQueryLayout
            top.instanceQueryLayout)).zipIdx := by
    rw [TopLevelCircuit.toVerifierKey_permutationChunks]
    exact Zcash.Snark.verifierCS_permutationChunks_flatten top
  calc
    ((vk.permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
        (vk.permutationChunks.flatten.getD
          global ((.advice 0), 0)).2 := by
      exact congrArg Prod.snd hlocal.symm
    _ =
        (((top.permutationColumns.map
          (Zcash.Snark.permutationQueryReference
            top.adviceQueryLayout
            top.fixedQueryLayout
            top.instanceQueryLayout)).zipIdx).getD
          global ((.advice 0), 0)).2 := by
      rw [hflatten]
    _ = global := zipIdx_getD_snd _ (ColumnRef.advice 0) global
      (by
        simp only [List.length_map]
        rw [← top.permutationColumnCount_eq_permutationColumns_length]
        exact hglobal)

variable [CircuitFieldSupport top]

def resolverPermutationCycle_or_relation
    (pp : ProofParams) (urs : URS G)
    (hk : top.domainExponent = urs.k)
    {instanceCommitment :
      Fin pp.numProofs → ℕ → G}
    {ps : ProofString (top.shape.withProofParams pp) Fp G}
    {ch : Challenges top.domainExponent Fp}
    {pU pW : Fp} {a : Fin (2 ^ urs.k) → Fp}
    {batchOpenings :
      OpenedBatchOpenings urs (evalVector urs.k ch.x3)
        (x4BatchCommitments
          (shape := top.shape.withProofParams pp)
          (instanceCommitment := instanceCommitment)
          urs hk
            (top.toVerifierKey urs) ps ch)
        (x4BatchEvals
          (shape := top.shape.withProofParams pp)
          (instanceCommitment := instanceCommitment)
          (top.toVerifierKey urs) ps ch)
        a pU pW}
    {memberDecode : ∀ i (hi : i <
        deployedX4PairCount
          (shape := top.shape.withProofParams pp)
          (instanceCommitment := instanceCommitment)
          (top.toVerifierKey urs) ps ch),
      OpenedMemberDecode
        (shape := top.shape.withProofParams pp)
        (instanceCommitment := instanceCommitment)
        urs hk
          (top.toVerifierKey urs) ps ch batchOpenings i hi}
    {y : Fp} {hpoly : CPoly} {deg : ℕ}
    (relation : CanonicalMemberConstraintRelation
      (shape := top.shape.withProofParams pp)
      urs hk
        (top.toVerifierKey urs) instanceCommitment ps ch pU pW a
      batchOpenings memberDecode
        (top.toVerifierKey_blindingFactors_lt_n urs)
        y hpoly deg)
    (proofIndex : Fin pp.numProofs) :
    ResolverPermutationCycleWitness
        (top.toVerifierKey urs) relation.polynomial proofIndex
        (top.usableRowsAt top.domainExponent)
        ((activeSigma top) pp urs relation.polynomial proofIndex)
      ⊕' AugmentedRelationWitness (F := Fp) urs.g urs.u urs.w := by
  classical
  have hkDomain : top.domainExponent = urs.k :=
    hk
  have hkUrs : urs.k ≤ 32 := by
    rw [← hkDomain]
    exact Nat.le_of_lt_succ top.domainExponent_lt
  let setup := LagrangePrefixSetup.ofDerived urs hkUrs
  have hcolumns : ∀
      (chunk : Fin top.permutationSetCount)
      (column : Fin
        (ResolverPermutationPairs
          (top.toVerifierKey urs) relation.polynomial
          proofIndex chunk).length),
      (ResolverPermutationPairs
        (top.toVerifierKey urs) relation.polynomial
        proofIndex chunk)[column].2 =
          keygenSigmaColumn
            top.omega Arithmetic.deltaFp top.chunkLen
            ((fullSigma top) pp urs relation.polynomial proofIndex)
            chunk column ⊕'
        AugmentedRelationWitness (F := Fp) urs.g urs.u urs.w := by
    intro chunk column
    let vk := top.toVerifierKey urs
    have hcommonIndex :=
      (chunkCommonIndex top) pp urs relation.polynomial proofIndex
        chunk column
    have hcommon :
        (chunk : ℕ) * top.chunkLen + (column : ℕ) <
          top.permutationColumnCount := by
      have hlt :=
        (((chunkFlatten top)
          pp urs relation.polynomial proofIndex
          ⟨chunk, ⟨0, top.n_pos⟩, column⟩).2).isLt
      simpa only [chunkFlatten_apply_column,
        columns_length] using hlt
    let common : Fin top.permutationColumnCount :=
      ⟨(chunk : ℕ) * top.chunkLen + (column : ℕ), hcommon⟩
    let shapeCommon : Fin top.permutationColumnCount :=
      common
    have homega :
        vk.omega = omegaOf urs.k := by
      simpa only [vk, top.toVerifierKey_omega, TopLevelCircuit.omega,
        Zcash.Arithmetic.pastaDomain_omega_eq] using congrArg omegaOf hkDomain
    let key : LagrangeCommitmentKey urs vk.omega := by
      let sourceKey :=
        LagrangeCommitmentKey.ofPrefix urs
          (omegaOf urs.k) (derivedUrsGLagrange urs)
          setup.generator_eq
      exact
        { generators := sourceKey.generators
          generator_eq := by
            intro i
            rw [homega]
            exact sourceKey.generator_eq i }
    have hcommit :
        vk.permutationCommonCommitment shapeCommon =
          key.commitInstance
            (topLevelPermutationRows
              top common) 1 := by
      simp only [vk]
      rw [top.toVerifierKey_permutationCommonCommitment]
      have source :=
        PermutationCommitmentCoherence.commitment_ofKeygen
          top urs hkDomain setup common
          common.isLt
      simpa only [topLevelPermutationCommitment, key,
        LagrangeCommitmentKey.commitInstance,
        LagrangeCommitmentKey.commitRows] using source
    have hj :
        (column : ℕ) <
          (vk.permutationChunks.getD chunk []).length := by
      simpa only [vk, ResolverPermutationPairs,
        permutationChunkPairsOfResolver, List.length_map] using
          column.isLt
    have hval :
        ∀ i : Fin top.n,
          (topLevelPermutationRows
            top common).getD (i : ℕ) 0 =
            chunkRowName vk.omega vk.delta vk.chunkLen
              ((fullSigma top)
                pp urs relation.polynomial proofIndex
                ⟨chunk, i, column⟩).1
              ((fullSigma top)
                pp urs relation.polynomial proofIndex
                ⟨chunk, i, column⟩).2.1
              ((fullSigma top)
                pp urs relation.polynomial proofIndex
                ⟨chunk, i, column⟩).2.2 := by
      intro i
      have source :=
        (permutationRows_eq_chunkRowName top)
          pp urs relation.polynomial proofIndex chunk column i
      have hcommonRow :
          (common : ℕ) =
            (((chunkFlatten top)
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).2 : ℕ) := by
        simp only [common,
          chunkFlatten_apply_column]
      rw [hcommonRow]
      simpa only [vk,
        top.toVerifierKey_omega,
        top.toVerifierKey_delta,
        top.toVerifierKey_chunkLen] using source
    have hidx :
        ((vk.permutationChunks.getD chunk [])[column]).2 =
          (shapeCommon : ℕ) := by
      calc
        ((vk.permutationChunks.getD chunk [])[column]).2 =
            ((vk.permutationChunks.getD chunk []).getD
              column ((.advice 0), 0)).2 :=
          congrArg Prod.snd (List.getD_eq_getElem _ _ hj).symm
        _ = ((top.verifierCS.permutationChunks.getD chunk []).getD
              column ((.advice 0), 0)).2 := by
          simp only [vk, top.toVerifierKey_permutationChunks]
        _ = (chunk : ℕ) * top.chunkLen + (column : ℕ) :=
          hcommonIndex
        _ = (common : ℕ) := (Fin.val_mk hcommon).symm
        _ = (shapeCommon : ℕ) := by
          simp only [shapeCommon]
    have hidentified :=
      relation.resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation_of_size
        proofIndex chunk column hj shapeCommon hidx key
        (topLevelPermutationRows
          top common)
        hcommit (by simpa only [top.toVerifierKey_omega] using top.domainRowsInjective_of_domainExponent_eq hk)
        (by
          simpa only [top.n_eq_two_pow_domainExponent] using
            congrArg (2 ^ ·) hkDomain)
        ((fullSigma top)
          pp urs relation.polynomial proofIndex)
        chunk column hval
    simpa only [top.toVerifierKey_omega,
      top.toVerifierKey_delta,
      top.toVerifierKey_chunkLen] using hidentified
  -- The successful cycle is returned as data; only its sigma equality is proof-valued.
  exact bindOrRelationWitness
    (finForallOrRelationWitness fun chunk =>
      finForallOrRelationWitness fun column => hcolumns chunk column)
    (fun hcolumns =>
      ⟨top.resolverPermutationCycleOfKeygenColumns urs relation.polynomial proofIndex
        top.usableRowsAt_domainExponent_le_n
        ((fullSigma top)
          pp urs relation.polynomial proofIndex)
        ((activeSigma top)
          pp urs relation.polynomial proofIndex)
        hcolumns
        ((activeSigma_widen top)
          pp urs relation.polynomial proofIndex),
        rfl⟩)

end TopLevelCopy

end Zcash.Snark
