-- Auto-generated by the sibling-checkout `ecc::chip::layout_dump::dump_layout_add`
-- (halo2_gadgets/src/ecc/chip/layout_dump.rs; Halo2-Clean VK matching). Do not edit by hand.
-- Regenerate:
--   cargo test --release -p halo2_gadgets --lib ecc::chip::layout_dump::dump_layout_add -- --nocapture
-- Minimal complete-addition harness (9 advices, add(a0..a8)): witness p/q (row 0),
-- one `add::Config::assign_region` (row 1). SimpleFloorPlanner keygen view, k=11,
-- Value::unknown().
import Zcash.Circuits.Fixtures.FixtureTypes

namespace Zcash.Circuits.Fixtures

open Fixtures

def addLayout : LayoutFixture :=
  { k := 11,
    n := 2048,
    regions := [⟨0, "witness pq", 0⟩, ⟨1, "complete point addition", 1⟩],
    permColumns := [.advice 0, .advice 1, .advice 2, .advice 3],
    copyList := [(0, 1, 0, 0),
      (1, 1, 1, 0),
      (2, 1, 2, 0),
      (3, 1, 3, 0)],
    sigma := [(0, 0, 0, 1),
      (0, 1, 0, 0),
      (1, 0, 1, 1),
      (1, 1, 1, 0),
      (2, 0, 2, 1),
      (2, 1, 2, 0),
      (3, 0, 3, 1),
      (3, 1, 3, 0)],
    constants := [],
    fixed := [(0, 1, 1)] }

end Zcash.Circuits.Fixtures
