-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
import Zcash.Circuits.Fixtures.FixtureTypes

namespace Zcash.Circuits.Fixtures

open Fixtures

def addPost : CsFixture :=
  { numAdviceColumns := 9,
    numFixedColumns := 1,
    numInstanceColumns := 0,
    numSelectors := 1,
    adviceQueryLayout := [(0, 0), (1, 0), (2, 0), (3, 0), (2, 1), (3, 1), (4, 0), (5, 0), (6, 0), (7, 0), (8, 0)],
    fixedQueryLayout := [(0, 0)],
    instanceQueryLayout := [],
    gates := [(.product (.fixed 0) (.product (.sum (.advice 2) (.negated (.advice 0))) (.sum (.product (.sum (.advice 2) (.negated (.advice 0))) (.advice 6)) (.negated (.sum (.advice 3) (.negated (.advice 1))))))),
      (.product (.fixed 0) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.sum (.advice 2) (.negated (.advice 0))) (.advice 7)))) (.sum (.product (.product (.constant (mkFp 2 0 0 0)) (.advice 1)) (.advice 6)) (.negated (.product (.constant (mkFp 3 0 0 0)) (.product (.advice 0) (.advice 0))))))),
      (.product (.fixed 0) (.product (.product (.product (.advice 0) (.advice 2)) (.sum (.advice 2) (.negated (.advice 0)))) (.sum (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 0))) (.negated (.advice 2))) (.negated (.advice 4))))),
      (.product (.fixed 0) (.product (.product (.product (.advice 0) (.advice 2)) (.sum (.advice 2) (.negated (.advice 0)))) (.sum (.sum (.product (.advice 6) (.sum (.advice 0) (.negated (.advice 4)))) (.negated (.advice 1))) (.negated (.advice 5))))),
      (.product (.fixed 0) (.product (.product (.product (.advice 0) (.advice 2)) (.sum (.advice 3) (.advice 1))) (.sum (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 0))) (.negated (.advice 2))) (.negated (.advice 4))))),
      (.product (.fixed 0) (.product (.product (.product (.advice 0) (.advice 2)) (.sum (.advice 3) (.advice 1))) (.sum (.sum (.product (.advice 6) (.sum (.advice 0) (.negated (.advice 4)))) (.negated (.advice 1))) (.negated (.advice 5))))),
      (.product (.fixed 0) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.advice 0) (.advice 8)))) (.sum (.advice 4) (.negated (.advice 2))))),
      (.product (.fixed 0) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.advice 0) (.advice 8)))) (.sum (.advice 5) (.negated (.advice 3))))),
      (.product (.fixed 0) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.advice 2) (.advice 9)))) (.sum (.advice 4) (.negated (.advice 0))))),
      (.product (.fixed 0) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.advice 2) (.advice 9)))) (.sum (.advice 5) (.negated (.advice 1))))),
      (.product (.fixed 0) (.product (.sum (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.sum (.advice 2) (.negated (.advice 0))) (.advice 7)))) (.negated (.product (.sum (.advice 3) (.advice 1)) (.advice 10)))) (.advice 4))),
      (.product (.fixed 0) (.product (.sum (.sum (.constant (mkFp 1 0 0 0)) (.negated (.product (.sum (.advice 2) (.negated (.advice 0))) (.advice 7)))) (.negated (.product (.sum (.advice 3) (.advice 1)) (.advice 10)))) (.advice 5)))] }

end Zcash.Circuits.Fixtures
