-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Selector-compression map (see `compress_selectors.rs`): per selector, the packed
-- fixed column, its combination length, and this selector's assigned root.
import Zcash.Circuits.Fixtures.FixtureTypes

namespace Zcash.Circuits.Fixtures

open Fixtures

def mulSelMap : SelCompressMap :=
  { newFixedCols := 7,
    entries := [(0, ⟨2, 1, 1⟩),
      (1, ⟨3, 1, 1⟩),
      (2, ⟨4, 3, 1⟩),
      (3, ⟨5, 1, 1⟩),
      (4, ⟨4, 3, 2⟩),
      (5, ⟨4, 3, 3⟩),
      (6, ⟨6, 3, 1⟩),
      (7, ⟨6, 3, 2⟩),
      (8, ⟨7, 3, 1⟩),
      (9, ⟨6, 3, 3⟩),
      (10, ⟨7, 3, 2⟩),
      (11, ⟨8, 1, 1⟩),
      (12, ⟨7, 3, 3⟩)] }

end Zcash.Circuits.Fixtures
